# Site Settings
baseURL: "http://www.ericcarlisle.com/"
title: "Eric Carlisle : UI Developer, UX Designer"
copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
theme: "podium"
author:
  name: "Eric Carlisle"
  email: "eric@ericcarlisle.com"
languageCode: "en-US"
theme: "podium"
canonifyURLs: true
config: "config.toml"
enableGitInfo: true
enableRobotsTXT: true
googleAnalytics: ""
permalinks:
  blog: posts/:year/:month/:day/:slug/
  presentations: presentations/:year/:month/:day/:slug/
pygmentsuseclasses: false
publishdir: "site"
sitemap:
  changefreq: "weekly"
  priority: "0.5"
  filename: "sitemap.xml"
params:
  description: "Eric Carlisle is a UI Developer and UX Designer. His motto is KISS, to 'Keep it Stunningly Simple.'"
  DateForm: "Mon, Jan 2, 2006"
  headertitle:
    title: "Eric Carlisle"
    subtitle: "UI Developer, UX Designer"
  profile:
    image: "/img/global/eric-carlisle-300x300.png"
    name: "Eric Carlisle"
    title: "UI Developer, UX Designer"
  organization:
    name: "Eric Carlisle Consulting"
    logo:
      url: "assets/img/eric-carlisle-consuling-logo.png"
      height: "60"
      width: "600"
  social:
    facebook:
      admins: "eric.carlisle"
      appid: "616445445121972"
    twitter:
      username: "eric_carlisle"
    instagram:
      username: "ericcarlisle"
    github:
      username: "ecarlisle"
    medium:
      username: "@eric_carlisle"
    slideshare:
      username: "ericcarlisle"
Menu:
  main:
    - Name: "About"
      URL: "/about/"
      Weight: "100"

  main:
    - Name: "Home"
      URL: "/"
      Weight: "100"

    - Name: "About Me"
      URL: "/about/"
      Weight: "200"

    - Name: "Blog"
      URL: "/blog/"
      Weight: "300"

    - Name: "Presentations"
      URL: "/presentations/"
      Weight: "400"

    - Name: "Portfolio"
      URL: "/portfolio/"
      Weight: "500"
